### PR TITLE
Enhance colors handing in `svg-icon'

### PR DESCRIPTION
**Pull request by zevlg**
Some color names known to Emacs are not known to svg, for example
"red3".  This patch makes it possible to specify Emacs colors as
FG-COLOR and BG-COLOR arguments to `svg-icon`, they are converted to
svg colors.

Also, makes it possible to specify FG-COLOR and BG-COLOR as ordinary
Emacs faces.  For FG-COLOR `:foreground` attribute is taken as color,
for BG-COLOR `:background` attribute is taken as color.  If face has
no such attribute, then fallback to defaults.

### CODE REVIEW

**Comment by rougier** [comment]
Good point, I've never thought of that potential problem.

**Comment by a13** [comment]
@rougier @zevlg 
Nice work, guys, but I can't imagine a reason why a person may want to use two **different** emacs faces for fg/bg, I suppose optional arguments could be rewritten using keyword ones (`cl-defun`), so we can tell their "types".

Remembering `all-the-icons`, what I really like is it has a predefined hand-picked collection of faces (see https://github.com/domtronn/all-the-icons.el/blob/master/all-the-icons-faces.el), maybe we want to use something like that in this package as well?

**Comment by zevlg** [comment]
> @rougier @zevlg
> Nice work, guys, but I can't imagine a reason why a person may want to use two **different** emacs faces for fg/bg,

If you force only one face for both fg and bg, you won't be able to specify "transparent" background.  Current implementation is very flexible in this sense.

Problem with forced background color (which looks like "transparent" in the Emacs frame) is that you might need to display this icon in different contexts.  For example I have different background color for the modeline, and if background of 'default face is used for the icon, this icon will look ugly in the modeline.


> I suppose optional arguments could be rewritten using keyword ones (`cl-defun`), so we can tell their "types".

I vote for `cl-defun` as well for extensibility reasons.

**Comment by rougier** [comment]
fg and bg makes sense in conjunction with colors but I agree that for face, it would be better to use only ony one. And we could also use the box for stroke width & color.

**Pull request merged**
