### PR TITLE
Cleanup README

### PR DESCRIPTION
**Pull request by jasonm23**
Just a proof read + minor fixes.

### CODE REVIEW

**Comment by rougier** [comment]
Thanks! By the way, there's a now an improved package at [svg-lib](https://github.com/rougier/svg-lib/)

**Comment by jasonm23** [comment]
Yes, I saw that. Looks cool.

I'm building some clock face icon fonts, that may work nicely in svg-lib.  I'll update when they're ready.

WIP https://ocodo.github.io/ClockFace-font/

**Comment by rougier** [comment]
Oh, a svg-lib-clock function woudl be great indeed!

**Comment by jasonm23** [comment]
Unfortunately it'd probably crash emacs.

I'm not sure how clean the SVG-clock.el is but after 8 hours it tends to freeze Emacs.

**Comment by rougier** [comment]
Soory, I'm lost. Which svg-clock.el are you talking about?

**Comment by jasonm23** [comment]
https://elpa.gnu.org/packages/svg-clock.html

**Comment by rougier** [comment]
I see. I was thinking instead of having a static svg-lib-clock icon for a given time. Pretty much like the svg-lib-progress-pie.

**Comment by jasonm23** [comment]
have you figured out how to put images & SVG in the modeline (via overlays?)?

**Comment by rougier** [comment]
No need to use overlay, you can propertize a string and used the `display` propert to display the SVG and it will be displayed as a regular text.

**Comment by jasonm23** [comment]
If you've got some example code that places an SVG on the modeline. beyond the manual, that's what I'm looking for.

**Comment by rougier** [comment]
Best would be to use [svg-lib](https://github.com/rougier/svg-lib) and do something like:
```
(setq mode-line-format (propertize "Hello" 'display (svg-lib-tag "Hello")))
```

**Comment by jasonm23** [comment]
I meant any svg

**Comment by rougier** [comment]
`(setq mode-line-format (propertize "Hello" 'display (svg-image ...)))` and replace ... with your actual svg code.

**Comment by jasonm23** [comment]
Oh ok! I didn't see svg-image in the docs.  I'll try to find it.

**Pull request merged**
